### ISSUE TITLE
Strict Standards: Only variables should be passed by reference in nbbc.php on line 1445

### ISSUE THREAD

**Issue by xxluke** [theyak/nbbc#1]
This bug from 1.4.5 still exists: http://sourceforge.net/p/nbbc/bugs/29/
You get the error "Strict Standards: Only variables should be passed by reference in nbbc.php on line 1445" when you use for example lists with [*].

**Comment by theyak** [comment]
Need to rebuild nbbc.php. Looks like this can be done with the merge.pl script in the tools folder.
