### ISSUE TITLE
Illegal String Offset

### ISSUE THREAD

**Issue by Symbiote445** [theyak/nbbc#4]
When I use [code] tags, I get the error: **Warning: Illegal string offset '_tag' in /var/www/Deployer/sites/5807a685d1a9ab3b599035bc566ce2b9/include/scripts/nbbc_parse.php on line 2296** So far I have only encountered this with [code] tags.

**Comment by theyak** [comment]
Hi, can you please provide the exact string you are trying to parse?

**Comment by theyak** [comment]
Closed due to no response. Please open a new issue complete with bbcode sample if issue is still occurring.
